### ISSUE TITLE
broadcast_message example crashes occasionally 

### ISSUE THREAD

**Issue by tuxiqae** [bastion-rs/bastion#277] opened 2020-10-06 13:18 UTC
* **Version**: current `master` branch
  - bastion - `0.4.4-alpha.0`
  - bastion-executer -  `0.4.1-alpha.0`
  - lightproc -  `0.3.6-alpha.0`
* **Platform**: `Linux Host 5.8.13-zen1-2-zen #1 ZEN SMP PREEMPT Fri, 02 Oct 2020 15:14:58 +0000 x86_64 GNU/Linux`

I tried running the `broadcast_message.rs` example a couple of times (using `cargo run --example broadcast_message`), it ran perfectly fine the first 7 times, crashed on the 8th try, and ran perfectly well on the 9th+ runs.
It might've happened because the process of the 7th run didn't quit properly before the 8th was executed, not sure though because they had 5 seconds in-between.

Output of the last 3 runs attached.

[crash.log](https://github.com/bastion-rs/bastion/files/5333926/crash.log)

**Comment by o0Ignition0o** [comment] 2020-10-06 13:25
Oh that's interesting, i wonder if i can reproduce it !

**Comment by tuxiqae** [comment] 2020-10-06 13:31
Let me know if you need my help

**Comment by o0Ignition0o** [comment] 2021-02-03 16:27
Hey there, we merged quite a bit of stuff lately, is there any chance this cannot be reproduced anymore ? :)

**Comment by o0Ignition0o** [comment] 2021-04-07 08:05
Going to close this as I cannot reproduce it, please reopen it if it makes sense :)

**Closed by o0Ignition0o** 2021-04-07 08:05 UTC
